### ISSUE TITLE
Missing addping option

### ISSUE THREAD

**Issue by stephaneprovost** [gitbls/internet-monitor#5]
Hello, the getopt call is missing addping, resulting with the addping option being rejected by internet-monitor. 

The fix is trivial, happy to propose a PR if I get the necessary privileges =)

Great work by the way! Thanks!

**Comment by gitbls** [comment]
Thanks for the feedback. Apparently you missed this note in the readme:

**NOTE: This app is retired. Please see [imon](https://github.com/gitbls/imon) for an app that is based on this, but offers more flexibility and capabilities, and much better performance.**

Of course, feel free to continue using internet-monitor, but since it's retired, I won't be fixing anything in internet-monitor.

**Comment by stephaneprovost** [comment]
You're absolutely right, I missed that Note. Feel free to close that ticket, I'll move to imon.

**Comment by gitbls** [comment]
Perfect. I'm much happier with imon than this thing, which grew far beyond its original purpose 🤣
